Jtesar/chapter1 web console install
RedHatQuickCourses/rhods-admin pull request #1
Opened 2023-10-19 13:21 UTC by jtesar-rh

2023-10-24 03:21 UTC, rsriniva requested changes
This is an excellent start Jiri! Please address my PR comments

2023-10-24 03:21 UTC, rsriniva commented on modules/chapter1/pages/section1.adoc
> +== Installation of the Red{nbsp}Hat Openshift Pipelines operator
Please see how Jaime is structuring the sections in the first intro course. Add 2 or 3 paragraphs about the context for the exercise.You can talk about the following things mentioned in the design doc

- [Trevor] - This seems to focus on the self-managed install but doesn't talk at all about the managed service.  The difference between the two should be discussed somewhere in the training. Introduce the different ways you can install the product - CLI, web console etc. Talk about how different self managed is compared to managed RHODS. Separate product docs exist for the AWS managed version of the product. You can say this is out of scope for this course and that we will only cover self managed.
- Provide warnings about not choosing the community upstream OpenDataHub operators
- [Trevor] RHODS includes other dependencies outside of OpenShift Pipelines.  For GPU we require the NVIDIA GPU Operator, and the Node Feature Discovery Operator.

2023-10-24 03:21 UTC, rsriniva commented on modules/chapter1/pages/section1.adoc
> +
See and talk to Jaime about splitting this section into a separate sub-sections called "Exercise: Installing RHODS using the web console" and another sub-section called "Installing RHODS using the CLI". A third sub-section called "Troubleshooting" can be added. Finally, add a References section and provide links to all product docs etc plus any code and scripts you have written for CLI install. Provide links to appropriate scripts/code repo

2023-10-24 03:21 UTC, rsriniva commented on modules/chapter1/pages/section1.adoc
> +image::rhods_verify2.png[width=800]
Mention the fact that they should log in as cluster administrator using OCP credentials to do this initial checking of install status

2023-10-24 03:26 UTC, rsriniva commented on modules/chapter1/pages/section1.adoc
> +
Ignore my comment about separate sub section  for CLI install. I notice that you have added a separate section which is the better approach because of the length of the exercise. But please add a Troubleshooting and References section

2023-10-24 10:38 UTC, jramcast reviewed
Good job. I left some adoc suggestions.

2023-10-24 10:38 UTC, jramcast commented on modules/chapter1/pages/section1.adoc
> +*Red{nbsp}Hat Openshift Data Science* is installed as an operator. As a dependecy it requires the *Red{nbsp}Hat Openshift Pipelines* operator to be installed as well.
You might also mention (maybe as a note) that if they are planning to use GPUs, they must have the NVIDIA GPU operator installed too.

2023-10-24 10:38 UTC, jramcast commented on modules/chapter1/pages/section1.adoc
> +2. Navigate to **Operators** -> **OperatorHub** and seach for *Red{nbsp}Hat Openshift Pipelines*
(adoc) There is a menu macro that you can use for this kind of navigation

```suggestion
2. Navigate to menu:Operators[OperatorHub] and search for *Red{nbsp}Hat Openshift Pipelines*.
```


https://docs.asciidoctor.org/asciidoc/latest/macros/ui-macros/#menu-macro-syntax

2023-10-24 10:38 UTC, jramcast commented on modules/chapter1/pages/section1.adoc
> +2. Navigate to **Operators** -> **OperatorHub** and seach for *Red{nbsp}Hat Openshift Pipelines*
To use the menu macro, you must activate the `experimental` attribute in the project, like I did here https://github.com/RedHatQuickCourses/rhods-intro/blob/main/antora-playbook.yml#L11

2023-10-24 10:38 UTC, jramcast commented on modules/chapter1/pages/section1.adoc
> +4. In the installation view some installation parameters can be tuned. Administrator can set the *Update{nbsp}channel* parameter to a specific version and the *Update{nbsp}approval* parameter to eith
For UI buttons or other elements, you can use the button macro https://docs.asciidoctor.org/asciidoc/latest/macros/ui-macros/#button-macro-syntax

2023-10-24 10:38 UTC, jramcast commented on modules/chapter1/pages/section1.adoc
> +Click on the **Install** button at the bottom of to view the to proceed with the installation. A window showing the installation progress will pop up.
Example of use of the button macro (you have to enable experimental mode for this to work).

```suggestion
Click on the btn:[Install] button at the bottom to proceed with the installation. A window showing the installation progress will pop up.
```

2023-10-24 10:38 UTC, jramcast commented on modules/chapter1/pages/section1.adoc
> +When the operator is installed you can view it's details by clicking on **View{nbsp}Operator** button.
```suggestion
When the operator is installed you can view its details by clicking on **View{nbsp}Operator** button.
```

2023-10-26 15:40 UTC, strangiato commented on modules/chapter1/pages/section2.adoc
> +*Red{nbsp}Hat Openshift Data Science* is installed as an operator. As a dependecy it requires the *Red{nbsp}Hat Openshift Pipelines* operator to be installed as well.
OpenShift Pipelines is only required if you plan to install the Data Science Pipelines component.

2023-10-26 15:40 UTC, strangiato commented on modules/chapter1/pages/section2.adoc
> +4. In the installation view window choose the **Update Channel**, **Installed{nbsp}Namespace** and *Update approval** or accept default values and click on **Install* the button. The *Installation{nb
The default channel today installs the v1 operator which will be depreciated in the near future.  The last version of v1 operator should be released in the next week or two and v2 will be the default moving forward.

V2 is available in the alpha channel today but we be made available in stable before the end of the year.

2023-10-26 15:40 UTC, strangiato commented on modules/chapter1/pages/section2.adoc
> +Operator Installation progress window will pup up. The installation may take a couple of minutes.
With the v1 operator as part of the install the operator pod automatically installs all of the components in the background as part of the operator install which is why it takes so long.

With v2, only the operator is installed and a new object called a DataScienceCluster is a new required object that must be setup.  The "installing operator" screen will be a little bit different because of this required object and the user will have to take additional steps to create the DSC after the operator is installed.

The DSC will allow users to enable and disable specific components and have better control over what is installed on each cluster.

2023-10-26 15:54 UTC, jtesar-rh commented on modules/chapter1/pages/section2.adoc
> +4. In the installation view window choose the **Update Channel**, **Installed{nbsp}Namespace** and *Update approval** or accept default values and click on **Install* the button. The *Installation{nb
Yes, I know that. I asked specifically about whether we create the module for v1 or v2, because installation for v2 would look quite differently. The workshop is in November and v1 will still be the stable version then I guess . So I think we should finish the initial version of the modeule using v1 and update it when v2 becomes stable.

2023-10-26 15:57 UTC, jtesar-rh commented on modules/chapter1/pages/section2.adoc
> +Operator Installation progress window will pup up. The installation may take a couple of minutes.
I'd reply the same thing as to the previous comment. We should finalize the first version using v1 and then update to v2 once it becomes stable.

2023-10-26 16:24 UTC, jtesar-rh commented on modules/chapter1/pages/section2.adoc
> +*Red{nbsp}Hat Openshift Data Science* is installed as an operator. As a dependecy it requires the *Red{nbsp}Hat Openshift Pipelines* operator to be installed as well.
True, but the v1 operator installs the Data Science Pipelines component automatically so I see the pipelines operator as a dependency for v1. What do you think?

2023-10-26 16:46 UTC, strangiato commented on modules/chapter1/pages/section2.adoc
> +4. In the installation view window choose the **Update Channel**, **Installed{nbsp}Namespace** and *Update approval** or accept default values and click on **Install* the button. The *Installation{nb
Yeah, the current state of the transition of the operator does leave us in a bit of an awkward position.

Personally I still think the docs should be oriented towards the v2 operator.  The goal of the workshop is to enable internal resources to help deliver RHODS for customers.  By the time the people attending the workshop are actively working on an engagement with RHODS, v2 will be stable.

It doesn't seem like the best strategy to try to enable people with material and knowledge that will be out of data a month later.

At a minimum, for the workshop we should at least be discussing v2 and letting people know  that it is coming.  If the workshop is going to focus on v1 for the hands on stuff that is fine.

I would probably defer to Noel on what he thinks on this topic of how to handle this for the workshop.

Just as a general update around v2, it is very usable today.  The biggest piece that is missing that is holding it back from stable is the automation intended to handle the v1 to v2 migration.

2023-10-26 17:16 UTC, jtesar-rh commented on modules/chapter1/pages/section2.adoc
> +4. In the installation view window choose the **Update Channel**, **Installed{nbsp}Namespace** and *Update approval** or accept default values and click on **Install* the button. The *Installation{nb
Yeah, that's a fair point, I agree. I'll somehow include the v2 as well :-)

2023-11-01 21:29 UTC, closed without merging