Jtesar/chapter1 cli install
RedHatQuickCourses/rhods-admin pull request #3
Opened 2023-10-19 13:45 UTC by jtesar-rh

Initial CLI installation

2023-10-24 03:25 UTC, rsriniva requested changes
Excellent start once again Jiri!. My comments:

- please talk to Jaime about restructuring this into narrative followed by a step by step exercise just like you did in the web console install section
- Add references to your YAML files and scripts in git repo
- Numbered steps for exercise so that all students doing this can reproduce the steps on their own cluster. You do not have to force students to erase their already installed RHODS instance and redo this - in fact, call this fact out in a NOTE or IMPORTANT admonition. This section is for their knowledge only.
- Add a References sub section at the bottom
- Add some troubleshooting tips
- Provide links to product docs if any

2023-10-24 10:23 UTC, jramcast reviewed
I tested the instructions and they work like a charm. I was able to install the Pipelines and RHODS operators. Good job!

Other than a few minor style suggestions, I have left a comment to reestructure the section a bit, so that it follows the _context/narrative/intro + hands-on exercise_ that @rsriniva is proposing. No big changes required, just a minor title adjustment and the use of ordered lists and a more direct voice in the hands-on parts.

2023-10-24 10:23 UTC, jramcast commented on modules/chapter1/pages/section2.adoc
> +To install the *Red{nbsp}Hat Openshift Pipelines* operator the package manifest must be located.
I'd suggest using a more direct voice here. It might be easier for students to understand.

```suggestion
To install the *Red{nbsp}Hat Openshift Pipelines* operator, locate the `openshift-pipelines-operator-rh` package manifest.
```

2023-10-24 10:23 UTC, jramcast commented on modules/chapter1/pages/section2.adoc
> +oc describe packagemanifest openshift-pipelines-operator-rh -n openshift-marketplace
Consistency with other commands (add the `$` prompt). I'm also suggesting emphasis in the command.

```suggestion
$ *oc describe packagemanifest openshift-pipelines-operator-rh -n openshift-marketplace*
```

2023-10-24 10:23 UTC, jramcast commented on modules/chapter1/pages/section2.adoc
> +$ oc get packagemanifest
This is a long list, what if we grep the output? 

```suggestion
$ oc get packagemanifest | grep pipelines
```

2023-10-24 10:23 UTC, jramcast commented on modules/chapter1/pages/section2.adoc
> +Finally the operator's subscription can be created to start the installation
```suggestion
Finally the operator's subscription can be created to start the installation.
```

2023-10-24 10:23 UTC, jramcast commented on modules/chapter1/pages/section2.adoc
> +== Installation of an operator using CLI
As I understand this particular section, it gives students some context into the installation of operators with the CLI, whereas the other two sections are more focused on Pipelines as RHODS. My suggestion is to treat this section as introductory narrative context, maybe by adjusting the title a bit, and then in the latter two sections, use ordered lists to make these sections more hands-on.

So for example, for this title, I would choose something like this:

```suggestion
== Introduction to CLI-based operator installations
```

Then, in the remaining two sections, I would replace the normal paragraphs with numbered lists, in a much more direct tone (giving instructions to students), for example, for the pipelines operator:

1.  Verify that the Pipelines operator is available in the Red Hat operators catalogue.
```
$ oc get catalogsource ...
```
2. Locate the package manifest
```
$ oc get ...
```
3. Same with the other steps...

2023-10-24 10:26 UTC, jramcast commented on modules/chapter1/pages/section2.adoc
> +== Installation of an operator using CLI
You might want to take a look at [this section](https://redhatquickcourses.github.io/rhods-intro/rhods-intro/1.33/chapter3/section1.html) to get an idea of that _narrative +  exercise_ structure.

2023-11-01 21:28 UTC, jtesar-rh commented
The section  has been rewritten for Operator V2

2023-11-01 21:28 UTC, closed without merging